# Generated by Django 3.2.9 on 2021-12-04 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('expert', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('stack', models.TextField()),
                ('photo', models.ImageField(upload_to='photos/0')),
            ],
        ),
    ]
