# Generated by Django 3.2.9 on 2021-12-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studhack', '0002_auto_20211206_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('team', models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
