# Generated by Django 3.2.9 on 2021-12-06 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studhack', '0004_auto_20211206_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='studhack.tasks'),
        ),
    ]
