# Generated by Django 3.2.9 on 2021-12-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studhack', '0007_auto_20211207_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
