# Generated by Django 3.2.9 on 2021-12-20 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studhack', '0008_alter_tasks_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='photo',
            field=models.ImageField(null=True, upload_to='media/', verbose_name='Фото'),
        ),
    ]
